POST http://robertferreira.ddns.net:17000/quiz
Content-Type: application/json

{
  "id_class": "9a701066-27e2-49d2-ae07-0c0f8fea9524",
  "user": {
        "id": "8378ba1e-20a8-4163-8cfe-ea2dfd8792e9",
        "name": "Robert",
        "cpf": "1323454879",
        "birth_date": "2000-12-25",
        "id_company": "1566d92f-9119-44d5-830e-9c3f94eb657c",
        "types_user": {
          "id": "103925a9-9b8f-4a4f-a50a-1980d46d3d89",
          "name": "aluno",
          "description": null
        },
        "active": true
      },
  "number_question": 1,
  "date": "2022-10-18",
  "id_company": "1566d92f-9119-44d5-830e-9c3f94eb657c",
  "questions": [
    {
      "id_company": "1566d92f-9119-44d5-830e-9c3f94eb657c",
      "description": "Qual a capital do Brasil?",
      "number_answer": 1,
      "answers": [
        {
          "id_company": "1566d92f-9119-44d5-830e-9c3f94eb657c",
          "description": "Brasilia",
          "correct": true,
          "score": 4
        }
      ]
    }
  ]
}